# Experimento 4 - CLASSIFICAÇÃO NUMERICA

In [1]:
import os
import pandas as pd
from biosppy.signals import ecg
from tqdm import tqdm

In [2]:
# Diretorio dos arquivos
dir_data = r"C:\Users\Usuario\Documents\Experimentos Anteprojeto\MUSE - ECG DATASET\ECGData1"
dir_target = r"C:\Users\Usuario\Documents\Experimentos Anteprojeto\MUSE - ECG DATASET\Diagnostics.xlsx"

In [3]:
dfclas = pd.read_excel(dir_target)
dfclas.head()

FileName Rhythm       Beat  PatientAge  Gender   
0  MUSE_20180113_171327_27000   AFIB   RBBB TWC          85    MALE  \
1  MUSE_20180112_073319_29000     SB        TWC          59  FEMALE   
2  MUSE_20180111_165520_97000     SA       NONE          20  FEMALE   
3  MUSE_20180113_121940_44000     SB       NONE          66    MALE   
4  MUSE_20180112_122850_57000     AF  STDD STTC          73  FEMALE   

   VentricularRate  AtrialRate  QRSDuration  QTInterval  QTCorrected  RAxis   
0              117         234          114         356          496     81  \
1               52          52           92         432          401     76   
2               67          67           82         382          403     88   
3               53          53           96         456          427     34   
4              162         162          114         252          413     68   

   TAxis  QRSCount  QOnset  QOffset  TOffset  
0    -27        19     208      265      386  
1     42         8     215      261      431  
2     20        11     224      265      415  
3      3         9     219      267      447  
4    -40        26     228      285      354

In [4]:
nomes = []

for diretorio, subpastas, arquivos in tqdm(os.walk(dir_data)):
    for arquivo in arquivos:
        a = os.path.join(diretorio, arquivo)                      # Variável com o nome do Diretório do arquivo
        #df = pd.read_csv(a)                                       # Abre o arquivo do Diretório
        nomes.append(arquivo)                                        # Adiciona od dados BPM em uma lista


nomes

1it [00:00, 250.00it/s]


['MUSE_20180111_155115_19000.csv',
 'MUSE_20180111_155154_74000.csv',
 'MUSE_20180111_155203_15000.csv',
 'MUSE_20180111_155249_70000.csv',
 'MUSE_20180111_155542_84000.csv',
 'MUSE_20180111_155543_90000.csv',
 'MUSE_20180111_155633_99000.csv',
 'MUSE_20180111_155709_17000.csv',
 'MUSE_20180111_155710_23000.csv',
 'MUSE_20180111_155758_17000.csv',
 'MUSE_20180111_155839_67000.csv',
 'MUSE_20180111_155859_36000.csv',
 'MUSE_20180111_155903_57000.csv',
 'MUSE_20180111_155907_78000.csv',
 'MUSE_20180111_155945_02000.csv',
 'MUSE_20180111_160033_11000.csv',
 'MUSE_20180111_160037_37000.csv',
 'MUSE_20180111_160052_85000.csv',
 'MUSE_20180111_160053_89000.csv',
 'MUSE_20180111_160110_47000.csv',
 'MUSE_20180111_160117_84000.csv',
 'MUSE_20180111_160140_78000.csv',
 'MUSE_20180111_160141_83000.csv',
 'MUSE_20180111_160159_36000.csv',
 'MUSE_20180111_160201_47000.csv',
 'MUSE_20180111_160333_03000.csv',
 'MUSE_20180111_160334_09000.csv',
 'MUSE_20180111_160352_71000.csv',
 'MUSE_20180111_1603

In [5]:
indvíduo = []
classe = []
classe_numero = []
anomalia = []
listaBPM = []

for diretorio, subpastas, arquivos in tqdm(os.walk(dir_data)):
    for arquivo in arquivos:
        
        # Lista o Arquivo
        #print(arquivo)
        
        # Nome do indivíduo
        b = arquivo.replace(".csv","")                           # Define o nome do indivíduo, de acordo com o arquivo
        indvíduo.append(b)
        c = dfclas.loc[dfclas['FileName'] == b]                  # Procura a linha que tem os dados do indivído
        d = str(c['Rhythm'])                                     # Procura a coluna com os dados do indivíduo
        e = d.split()                                            # Separa os dados em strings
        #print(e[1])                                              # imprime somente o indice que tem a classificação
        classe.append(e[1])
        
        # Classificação binaria anomalia = 1, normal = 0
        if e[1] == 'SN':
            #print('1')
            anomalia.append(1)
        else:
            #print('0')
            anomalia.append(0)
        
        # Classificação anoalia para inteiros
        if e[1] == 'SB': 
            # Sinus Bradycardia
            classe_numero.append(1)
        elif e[1] == 'SR':
            # Sinus Rhythm
            classe_numero.append(2)
        elif e[1] == 'AFIB':
            # Atrial Fibrillation
            classe_numero.append(3)
        elif e[1] == 'ST':
            # Sinus Tachycardia
            classe_numero.append(4)
        elif e[1] == 'AF':
            # Atrial Flutter
            classe_numero.append(5)
        elif e[1] == 'SI':
            # Sinus Irregularity
            classe_numero.append(6)
        elif e[1] == 'SVT':
            # Supraventricular Tachycardia
            classe_numero.append(7)
        elif e[1] == 'AT':
            # Atrial Tachycardia
            classe_numero.append(8)
        elif e[1] == 'AVNRT':
            # Atrioventricular  Node Reentrant Tachycardia
            classe_numero.append(9)
        elif e[1] == 'AVRT':
            # Atrioventricular Reentrant Tachycardia
            classe_numero.append(10)
        elif e[1] == 'SAAWR':
            # Sinus Atrium to Atrial Wandering Rhythm
            classe_numero.append(11)      
        else:
            classe_numero.append(20)
        
        # Converte BPM
        a = os.path.join(diretorio, arquivo)                      # Variável com o nome do Diretório do arquivo
        df = pd.read_csv(a)                                       # Abre o arquivo do Diretório
        y = df["II"].values                                       # Valores para y correspondem a Temperatura aparente
        out = ecg.ecg(signal=y, sampling_rate=500., show=False)   # Insere os dados na biblioteca SSPY
        z = out['heart_rate']                                     # Extrai os dados em BPM
        listaBPM.append(z)                                        # Adiciona od dados BPM em uma lista
       
"""        s1 = pd.Series([b, classe, anomalia, z])

        df = pd.DataFrame([list(s1)],  columns =  ["Nome", "Classe", "Anomalia", "BPM"])
        df
"""

listaBPM


1it [00:08,  8.95s/it]


[array([131.23061796, 126.66537003, 123.73989647, 123.37773509,
        125.01750946, 126.43023814, 126.79239952, 128.57353375,
        128.75694595, 124.63194182, 123.72258637, 123.90757971,
        130.34258615, 130.70168481, 125.33408559, 121.78281648,
        120.72340092, 125.9060068 , 127.3306858 ]),
 array([114.03818953, 102.95237937,  91.09640747, 113.73729715,
        119.86278986, 116.92665088, 103.89754712, 102.09379532,
        110.12183693, 110.47979798, 109.63804714, 105.42929293,
        113.997114  , 125.74056476, 132.39311174, 129.4256491 ]),
 array([66.81256097, 75.43377035, 79.5676889 , 71.69135637, 56.49653411,
        48.11067098, 44.77937202, 58.6673891 , 70.23373788]),
 array([117.21932233, 117.21932233, 117.06370937, 118.42146214,
        116.91858413, 116.91858413, 116.76297117, 118.11023622,
        117.80265748, 116.45539243, 116.30099996, 116.76419166,
        118.11145671, 117.95827044, 116.45539243, 116.30099996,
        116.76419166, 118.26706967]),
 arra

In [6]:
classe_numero

[4,
 3,
 3,
 4,
 5,
 4,
 7,
 20,
 20,
 1,
 1,
 1,
 3,
 1,
 3,
 1,
 4,
 4,
 3,
 3,
 3,
 3,
 1,
 3,
 3,
 3,
 4,
 4,
 1,
 1,
 3,
 4,
 4,
 4,
 1,
 3,
 4,
 1,
 3,
 20,
 3,
 20,
 2,
 3,
 1,
 1,
 1,
 1,
 1,
 7,
 1,
 3,
 3,
 3,
 1,
 4,
 1,
 4,
 4,
 1,
 4,
 7,
 7,
 4,
 3,
 4,
 3,
 8,
 4,
 3,
 4,
 7,
 3,
 3,
 1,
 4,
 1,
 3,
 7,
 4,
 4,
 5,
 7,
 3,
 1,
 3,
 7,
 4,
 3,
 4,
 4,
 4,
 4,
 20,
 3,
 1,
 7,
 3,
 7,
 3,
 7,
 4,
 1,
 4,
 4,
 1,
 3,
 4,
 4,
 20,
 4,
 4,
 1,
 4,
 4,
 1,
 1,
 1,
 20,
 4,
 20,
 1,
 3,
 4,
 1,
 3,
 3,
 3,
 4,
 4,
 3,
 3,
 3,
 3,
 3,
 3,
 1,
 1,
 1,
 4,
 4,
 4,
 4,
 4,
 1,
 1,
 8,
 20,
 1,
 1,
 1,
 1,
 3,
 1,
 1,
 1,
 20,
 1,
 3,
 3,
 3,
 3,
 3,
 1,
 1,
 1,
 1,
 4,
 1,
 1,
 1,
 20,
 1,
 1,
 1,
 4,
 1,
 3,
 3,
 1,
 3,
 3,
 3,
 1,
 1,
 1,
 1,
 1,
 1,
 4,
 1,
 1,
 4,
 1,
 1,
 20,
 1,
 3,
 4,
 20,
 7,
 1,
 4,
 4,
 3,
 1,
 1,
 3,
 7,
 1,
 1,
 4,
 7,
 1,
 3,
 3,
 1,
 1,
 1,
 7,
 1,
 1,
 20,
 1,
 1,
 4,
 1,
 2,
 1,
 4,
 1,
 4,
 4,
 4,
 4,
 1,
 1,
 4,
 5,
 4,
 1,
 9,
 7,
 20,
 7,
 4,
 

In [7]:
"""s1 = pd.Series([5, 6, 7])
s2 = pd.Series([7, 8, 9])"""

df1 = pd.DataFrame(columns =  ["Indivíduo", "Classe", "Classe Numero", "Anomalia", "BPM"])
i = 0

for item in indvíduo:
    df1.loc[i] = [indvíduo[i], classe[i], classe_numero[i], anomalia[i], listaBPM[i]]  # adding a row
    i += 1
    
    
df1

Indivíduo Classe  Classe Numero  Anomalia   
0    MUSE_20180111_155115_19000     ST              4         0  \
1    MUSE_20180111_155154_74000   AFIB              3         0   
2    MUSE_20180111_155203_15000   AFIB              3         0   
3    MUSE_20180111_155249_70000     ST              4         0   
4    MUSE_20180111_155542_84000     AF              5         0   
..                          ...    ...            ...       ...   
383  MUSE_20180112_074337_14000     SB              1         0   
384  MUSE_20180112_074344_49000     SB              1         0   
385  MUSE_20180112_074345_57000   AFIB              3         0   
386  MUSE_20180112_074357_84000     ST              4         0   
387  MUSE_20180112_074418_57000     ST              4         0   

                                                   BPM  
0    [131.23061795628166, 126.66537002820186, 123.7...  
1    [114.03818953323903, 102.95237937024766, 91.09...  
2    [66.81256097239432, 75.43377035323475, 79.5676...  
3    [117.21932233050717, 117.21932233050718, 117.0...  
4    [85.76932270356154, 80.37721540062621, 93.7789...  
..                                                 ...  
383  [54.885980514481396, 54.61761419445456, 55.398...  
384  [52.2060522060522, 53.03318206544013, 53.09182...  
385  [105.57658233820152, 95.9910103990758, 90.7118...  
386  [131.77384914298904, 130.639440642488, 129.690...  
387  [128.02327695944717, 128.02327695944714, 128.2...  

[388 rows x 5 columns]

In [8]:
X = listaBPM
X

[array([131.23061796, 126.66537003, 123.73989647, 123.37773509,
        125.01750946, 126.43023814, 126.79239952, 128.57353375,
        128.75694595, 124.63194182, 123.72258637, 123.90757971,
        130.34258615, 130.70168481, 125.33408559, 121.78281648,
        120.72340092, 125.9060068 , 127.3306858 ]),
 array([114.03818953, 102.95237937,  91.09640747, 113.73729715,
        119.86278986, 116.92665088, 103.89754712, 102.09379532,
        110.12183693, 110.47979798, 109.63804714, 105.42929293,
        113.997114  , 125.74056476, 132.39311174, 129.4256491 ]),
 array([66.81256097, 75.43377035, 79.5676889 , 71.69135637, 56.49653411,
        48.11067098, 44.77937202, 58.6673891 , 70.23373788]),
 array([117.21932233, 117.21932233, 117.06370937, 118.42146214,
        116.91858413, 116.91858413, 116.76297117, 118.11023622,
        117.80265748, 116.45539243, 116.30099996, 116.76419166,
        118.11145671, 117.95827044, 116.45539243, 116.30099996,
        116.76419166, 118.26706967]),
 arra

In [9]:
y = classe_numero
y

[4,
 3,
 3,
 4,
 5,
 4,
 7,
 20,
 20,
 1,
 1,
 1,
 3,
 1,
 3,
 1,
 4,
 4,
 3,
 3,
 3,
 3,
 1,
 3,
 3,
 3,
 4,
 4,
 1,
 1,
 3,
 4,
 4,
 4,
 1,
 3,
 4,
 1,
 3,
 20,
 3,
 20,
 2,
 3,
 1,
 1,
 1,
 1,
 1,
 7,
 1,
 3,
 3,
 3,
 1,
 4,
 1,
 4,
 4,
 1,
 4,
 7,
 7,
 4,
 3,
 4,
 3,
 8,
 4,
 3,
 4,
 7,
 3,
 3,
 1,
 4,
 1,
 3,
 7,
 4,
 4,
 5,
 7,
 3,
 1,
 3,
 7,
 4,
 3,
 4,
 4,
 4,
 4,
 20,
 3,
 1,
 7,
 3,
 7,
 3,
 7,
 4,
 1,
 4,
 4,
 1,
 3,
 4,
 4,
 20,
 4,
 4,
 1,
 4,
 4,
 1,
 1,
 1,
 20,
 4,
 20,
 1,
 3,
 4,
 1,
 3,
 3,
 3,
 4,
 4,
 3,
 3,
 3,
 3,
 3,
 3,
 1,
 1,
 1,
 4,
 4,
 4,
 4,
 4,
 1,
 1,
 8,
 20,
 1,
 1,
 1,
 1,
 3,
 1,
 1,
 1,
 20,
 1,
 3,
 3,
 3,
 3,
 3,
 1,
 1,
 1,
 1,
 4,
 1,
 1,
 1,
 20,
 1,
 1,
 1,
 4,
 1,
 3,
 3,
 1,
 3,
 3,
 3,
 1,
 1,
 1,
 1,
 1,
 1,
 4,
 1,
 1,
 4,
 1,
 1,
 20,
 1,
 3,
 4,
 20,
 7,
 1,
 4,
 4,
 3,
 1,
 1,
 3,
 7,
 1,
 1,
 4,
 7,
 1,
 3,
 3,
 1,
 1,
 1,
 7,
 1,
 1,
 20,
 1,
 1,
 4,
 1,
 2,
 1,
 4,
 1,
 4,
 4,
 4,
 4,
 1,
 1,
 4,
 5,
 4,
 1,
 9,
 7,
 20,
 7,
 4,
 

In [10]:
import numpy as np
from sklearn.model_selection import train_test_split

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [12]:
X_train = np.asarray(X_train)
y_train = np.asarray(y_train)
X_test = np.asarray(X_test)
y_test = np.asarray(y_test)

C:\Users\Usuario\AppData\Local\Temp\ipykernel_5512\2127771706.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  X_train = np.asarray(X_train)
C:\Users\Usuario\AppData\Local\Temp\ipykernel_5512\2127771706.py:3: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  X_test = np.asarray(X_test)


In [13]:

import tensorflow as tf
from tensorflow.keras.datasets import imdb
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing import sequence
# fix random seed for reproducibility
tf.random.set_seed(7)

In [14]:

# truncate and pad input sequences
max_review_length = 16
X_train = sequence.pad_sequences(X_train, maxlen=max_review_length)
X_test = sequence.pad_sequences(X_test, maxlen=max_review_length)

In [15]:
X_train[15]

array([ 0,  0,  0,  0,  0,  0,  0, 57, 56, 55, 54, 80, 76, 77, 74, 99])

In [16]:
# create the model
top_words = 200
embedding_vecor_length = 5
model = Sequential()
model.add(Embedding(top_words, embedding_vecor_length, input_length=max_review_length))
model.add(LSTM(10))
model.add(Dense(1, activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
print(model.summary())
model.fit(X_train, y_train, validation_data=(X_test, y_test), epochs=3, batch_size=64)

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 16, 5)             1000      
                                                                 
 lstm (LSTM)                 (None, 10)                640       
                                                                 
 dense (Dense)               (None, 1)                 11        
                                                                 
Total params: 1,651
Trainable params: 1,651
Non-trainable params: 0
_________________________________________________________________
None
Epoch 1/3
5/5 [==============================] - 3s 142ms/step - loss: 0.6678 - accuracy: 0.2973 - val_loss: 0.6034 - val_accuracy: 0.3721
Epoch 2/3
5/5 [==============================] - 0s 28ms/step - loss: 0.5797 - accuracy: 0.4286 - val_loss: 0.5008 - val_accuracy: 0.3721
Epoch 3/3
5/5 [=====================

In [17]:

# Final evaluation of the model
scores = model.evaluate(X_test, y_test, verbose=0)
print("Accuracy: %.2f%%" % (scores[1]*100))

Accuracy: 37.21%
